"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideNav from "@/components/SideNav";
import { usePathname } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const pathname = usePathname();
	const isHomePage = pathname === "/";
	console.log("home", isHomePage);
	return (
		<html lang="en" className="dark" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-gray-900 `}
			>
				{/* <ThemeProvider> */}
				<Header />
				<div className="grid grid-cols-7 items-center">
					<div className={isHomePage ? "hidden" : "col-span-1"}>
						<SideNav />
					</div>
					{/* <AnimatePresence mode="wait" initial={false}> */}
					<motion.div
						key={pathname}
						className={`${isHomePage ? "col-span-7" : "col-span-6"} w-full `}
					>
						{children}
					</motion.div>
				</div>
				{/* </AnimatePresence> */}
				<Footer />
				{/* </ThemeProvider> */}
			</body>
		</html>
	);
}
