"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideNav from "@/components/SideNav";
import { usePathname } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const pathname = usePathname();

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Header />
				<SideNav />
				{/* <AnimatePresence mode="wait" initial={false}> */}
				<motion.div
					key={pathname}
					className={`${pathname === "/" ? "" : "ml-64"} p-6`}
				>
					{children}
				</motion.div>
				{/* </AnimatePresence> */}
				<Footer />
			</body>
		</html>
	);
}
